-- 코드를 입력하세요
SELECT
A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_OUTS A
JOIN 
(
    SELECT ANIMAL_ID FROM ANIMAL_INS 
    WHERE SEX_UPON_INTAKE LIKE '%Intact%'
)
B USING(ANIMAL_ID)
WHERE A.SEX_UPON_OUTCOME NOT LIKE '%Intact%'
ORDER BY 1