-- 코드를 입력하세요
SELECT
YEAR(A.SALES_DATE) AS YEAR,
MONTH(A.SALES_DATE) AS MONTH,
B.GENDER AS GENDER, 
COUNT(DISTINCT B.USER_ID) AS USERS
FROM ONLINE_SALE A
JOIN USER_INFO B USING(USER_ID)
WHERE B.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1, 2, 3