-- 코드를 입력하세요
SELECT
YEAR(A.SALES_DATE) AS YEAR,
MONTH(A.SALES_DATE) AS MONTH,
COUNT(DISTINCT A.USER_ID) AS PUCHASED_USERS,
ROUND(COUNT(DISTINCT A.USER_ID) /( 
    SELECT COUNT(USER_ID) FROM USER_INFO 
    WHERE YEAR(JOINED) = '2021'), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE A INNER JOIN USER_INFO B USING(USER_ID)
WHERE A.USER_ID IN (SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = '2021')
GROUP BY YEAR, MONTH
ORDER BY 1, 2